package com.swych.mobile.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.swych.mobile.db.book;

import com.swych.mobile.db.bookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;

    private final bookDao bookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(bookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        bookDao = new bookDao(bookDaoConfig, this);

        registerDao(book.class, bookDao);
    }
    
    public void clear() {
        bookDaoConfig.getIdentityScope().clear();
    }

    public bookDao getBookDao() {
        return bookDao;
    }

}
