package com.swych.mobile.db;

import com.swych.mobile.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MAPPING.
 */
public class Mapping {

    private long id;
    private String strMapping;
    private Long version1_id;
    private Long version2_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MappingDao myDao;

    private Version nativeVersion;
    private Long nativeVersion__resolvedKey;

    private Version foreignVersion;
    private Long foreignVersion__resolvedKey;


    public Mapping() {
    }

    public Mapping(long id) {
        this.id = id;
    }

    public Mapping(long id, String strMapping, Long version1_id, Long version2_id) {
        this.id = id;
        this.strMapping = strMapping;
        this.version1_id = version1_id;
        this.version2_id = version2_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMappingDao() : null;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getStrMapping() {
        return strMapping;
    }

    public void setStrMapping(String strMapping) {
        this.strMapping = strMapping;
    }

    public Long getVersion1_id() {
        return version1_id;
    }

    public void setVersion1_id(Long version1_id) {
        this.version1_id = version1_id;
    }

    public Long getVersion2_id() {
        return version2_id;
    }

    public void setVersion2_id(Long version2_id) {
        this.version2_id = version2_id;
    }

    /** To-one relationship, resolved on first access. */
    public Version getNativeVersion() {
        Long __key = this.version1_id;
        if (nativeVersion__resolvedKey == null || !nativeVersion__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            VersionDao targetDao = daoSession.getVersionDao();
            Version nativeVersionNew = targetDao.load(__key);
            synchronized (this) {
                nativeVersion = nativeVersionNew;
            	nativeVersion__resolvedKey = __key;
            }
        }
        return nativeVersion;
    }

    public void setNativeVersion(Version nativeVersion) {
        synchronized (this) {
            this.nativeVersion = nativeVersion;
            version1_id = nativeVersion == null ? null : nativeVersion.getId();
            nativeVersion__resolvedKey = version1_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Version getForeignVersion() {
        Long __key = this.version2_id;
        if (foreignVersion__resolvedKey == null || !foreignVersion__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            VersionDao targetDao = daoSession.getVersionDao();
            Version foreignVersionNew = targetDao.load(__key);
            synchronized (this) {
                foreignVersion = foreignVersionNew;
            	foreignVersion__resolvedKey = __key;
            }
        }
        return foreignVersion;
    }

    public void setForeignVersion(Version foreignVersion) {
        synchronized (this) {
            this.foreignVersion = foreignVersion;
            version2_id = foreignVersion == null ? null : foreignVersion.getId();
            foreignVersion__resolvedKey = version2_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
