package com.swych.mobile.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.swych.mobile.db.Sentence;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SENTENCE.
*/
public class SentenceDao extends AbstractDao<Sentence, Long> {

    public static final String TABLENAME = "SENTENCE";

    /**
     * Properties of entity Sentence.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sentence_id = new Property(1, long.class, "sentence_id", false, "SENTENCE_ID");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Version_id = new Property(3, long.class, "version_id", false, "VERSION_ID");
    };

    private DaoSession daoSession;

    private Query<Sentence> version_SentencesQuery;

    public SentenceDao(DaoConfig config) {
        super(config);
    }
    
    public SentenceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SENTENCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SENTENCE_ID' INTEGER NOT NULL ," + // 1: sentence_id
                "'CONTENT' TEXT NOT NULL ," + // 2: content
                "'VERSION_ID' INTEGER NOT NULL );"); // 3: version_id
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SENTENCE_SENTENCE_ID ON SENTENCE" +
                " (SENTENCE_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SENTENCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Sentence entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSentence_id());
        stmt.bindString(3, entity.getContent());
        stmt.bindLong(4, entity.getVersion_id());
    }

    @Override
    protected void attachEntity(Sentence entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Sentence readEntity(Cursor cursor, int offset) {
        Sentence entity = new Sentence( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // sentence_id
            cursor.getString(offset + 2), // content
            cursor.getLong(offset + 3) // version_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Sentence entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSentence_id(cursor.getLong(offset + 1));
        entity.setContent(cursor.getString(offset + 2));
        entity.setVersion_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Sentence entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Sentence entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "sentences" to-many relationship of Version. */
    public List<Sentence> _queryVersion_Sentences(long version_id) {
        synchronized (this) {
            if (version_SentencesQuery == null) {
                QueryBuilder<Sentence> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Version_id.eq(null));
                queryBuilder.orderRaw("SENTENCE_ID ASC");
                version_SentencesQuery = queryBuilder.build();
            }
        }
        Query<Sentence> query = version_SentencesQuery.forCurrentThread();
        query.setParameter(0, version_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getVersionDao().getAllColumns());
            builder.append(" FROM SENTENCE T");
            builder.append(" LEFT JOIN VERSION T0 ON T.'VERSION_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Sentence loadCurrentDeep(Cursor cursor, boolean lock) {
        Sentence entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Version version = loadCurrentOther(daoSession.getVersionDao(), cursor, offset);
         if(version != null) {
            entity.setVersion(version);
        }

        return entity;    
    }

    public Sentence loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Sentence> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Sentence> list = new ArrayList<Sentence>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Sentence> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Sentence> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
